/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IMSUIs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sriyanjith Herath
 */
public final class CusViewUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuUI
     */
    public CusViewUI() {
        initComponents();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_db?zeroDateTimeBehavior=convertToNull", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        UpdateTable();

    }

    String Name;

    public CusViewUI(String name) {
        initComponents();

    }

    Connection con;
    PreparedStatement sta;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        UserLbl = new javax.swing.JLabel();
        ItemLbl = new javax.swing.JLabel();
        GRnLbl = new javax.swing.JLabel();
        CusLbl = new javax.swing.JLabel();
        SupLbl = new javax.swing.JLabel();
        ExitLbl = new javax.swing.JLabel();
        InvLbl = new javax.swing.JLabel();
        RepoLbl = new javax.swing.JLabel();
        LoginLbl = new javax.swing.JLabel();
        LogoPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CusTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AddTxt = new javax.swing.JTextField();
        CityTxt = new javax.swing.JTextField();
        ContMTxt = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LNameTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ContWTxt = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        FNameTxt = new javax.swing.JTextField();
        DFelBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELECTRO WORLD");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        UserLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserLbl.setForeground(new java.awt.Color(255, 255, 255));
        UserLbl.setText(" User Registration");
        UserLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserLblMouseClicked(evt);
            }
        });

        ItemLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ItemLbl.setForeground(new java.awt.Color(255, 255, 255));
        ItemLbl.setText(" Item Registration");
        ItemLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ItemLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemLblMouseClicked(evt);
            }
        });

        GRnLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GRnLbl.setForeground(new java.awt.Color(255, 255, 255));
        GRnLbl.setText(" GRN");
        GRnLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        GRnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRnLblMouseClicked(evt);
            }
        });

        CusLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CusLbl.setForeground(new java.awt.Color(255, 255, 255));
        CusLbl.setText(" Customer Registration");
        CusLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CusLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusLblMouseClicked(evt);
            }
        });

        SupLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SupLbl.setForeground(new java.awt.Color(255, 255, 255));
        SupLbl.setText(" Supplier Registration");
        SupLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SupLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupLblMouseClicked(evt);
            }
        });

        ExitLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExitLbl.setForeground(new java.awt.Color(255, 255, 255));
        ExitLbl.setText(" Exit");
        ExitLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLblMouseClicked(evt);
            }
        });

        InvLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InvLbl.setForeground(new java.awt.Color(255, 255, 255));
        InvLbl.setText(" Invoice");
        InvLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InvLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvLblMouseClicked(evt);
            }
        });

        RepoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RepoLbl.setForeground(new java.awt.Color(0, 153, 204));
        RepoLbl.setText(" Search");
        RepoLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RepoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepoLblMouseClicked(evt);
            }
        });

        LoginLbl.setBackground(new java.awt.Color(102, 255, 255));
        LoginLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginLbl.setForeground(new java.awt.Color(255, 255, 255));
        LoginLbl.setText(" User Login");
        LoginLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SupLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GRnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InvLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CusLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(ExitLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RepoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(LoginLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InvLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LogoPanel.setBackground(new java.awt.Color(51, 51, 51));
        LogoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LogoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Customers");

        CusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Address", "City", "Email", "Mobile No", "Home No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CusTable);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AddTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        CityTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ContMTxt.setColumns(10);
        try {
            ContMTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ContMTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Email");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Customer Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Mobile No.");

        LNameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        EmailTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Contact Nos.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("City");

        ContWTxt.setColumns(10);
        try {
            ContWTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ContWTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Home No.");

        FNameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContWTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(274, 274, 274))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EmailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LNameTxt))
                            .addComponent(AddTxt))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LNameTxt)
                    .addComponent(FNameTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ContMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ContWTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        DFelBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DFelBtn.setText("DELETE");
        DFelBtn.setPreferredSize(new java.awt.Dimension(67, 25));
        DFelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFelBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DFelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DFelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBtn))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void UpdateTable() {
        try {
            int c;
            sta = con.prepareStatement("SELECT * FROM customer");
            ResultSet res = sta.executeQuery();

            ResultSetMetaData rsd = res.getMetaData();
            c = rsd.getColumnCount();

            DefaultTableModel model1 = (DefaultTableModel) CusTable.getModel();
            model1.setRowCount(0);

            while (res.next()) {
                Vector vec = new Vector();
                for (int i = 0; i <= c; i++) {
                    vec.add(res.getString("cus_id"));
                    vec.add(res.getString("f_name"));
                    vec.add(res.getString("l_name"));
                    vec.add(res.getString("address"));
                    vec.add(res.getString("city"));
                    vec.add(res.getString("email"));
                    vec.add(res.getString("M_No"));
                    vec.add(res.getString("W_No"));
                }
                model1.addRow(vec);
            }

        } catch (SQLException ex) {
            Logger.getLogger(CusViewUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ResetForm() {
        FNameTxt.setText("");
        LNameTxt.setText("");
        AddTxt.setText("");
        CityTxt.setText("");
        EmailTxt.setText("");
        ContMTxt.setText("");
        ContWTxt.setText("");

    }

    private void LoginLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLblMouseClicked
        this.hide();
        new LoginUI().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_LoginLblMouseClicked

    private void UserLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLblMouseClicked
        this.hide();
        new UserRegUI().setVisible(true);
    }//GEN-LAST:event_UserLblMouseClicked

    private void SupLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupLblMouseClicked
        this.hide();
        new SupRegUI().setVisible(true);
    }//GEN-LAST:event_SupLblMouseClicked

    private void ItemLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemLblMouseClicked
        this.hide();
        new ItemRegUI().setVisible(true);
    }//GEN-LAST:event_ItemLblMouseClicked

    private void CusLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusLblMouseClicked
        this.hide();
        new CusRegUI().setVisible(true);
    }//GEN-LAST:event_CusLblMouseClicked

    private void InvLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvLblMouseClicked
        this.hide();
        new InvoiceUI().setVisible(true);
    }//GEN-LAST:event_InvLblMouseClicked

    private void GRnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRnLblMouseClicked
        this.hide();
        new GRNUI().setVisible(true);    }//GEN-LAST:event_GRnLblMouseClicked

    private void RepoLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepoLblMouseClicked
        this.hide();
        new SearchUI().setVisible(true);
    }//GEN-LAST:event_RepoLblMouseClicked

    private void ExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLblMouseClicked

    private void LogoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoPanelMouseClicked
        this.hide();
        new MenuUI().setVisible(true);
    }//GEN-LAST:event_LogoPanelMouseClicked

    private void DFelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFelBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) CusTable.getModel();
        int row = CusTable.getSelectedRow();

        int id = Integer.parseInt(model.getValueAt(row, 0).toString());
        
        int resDialog = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "CUSTOMER DETAILS", JOptionPane.YES_NO_OPTION);
        
        if (resDialog == JOptionPane.YES_OPTION){
            try {
                //initialized on top

                sta = con.prepareStatement("DELETE FROM customer WHERE cus_id=?");
                sta.setInt(1,id);

                sta.executeUpdate();
                JOptionPane.showMessageDialog(this, "Customer Details deleted Successfully ", "CUSTOMER DETAILS", JOptionPane.INFORMATION_MESSAGE);
                ResetForm();
                UpdateTable();
                
            } catch (SQLException ex) {
                Logger.getLogger(UserRegUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_DFelBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) CusTable.getModel();
        int row = CusTable.getSelectedRow();

        int id = Integer.parseInt(model.getValueAt(row, 0).toString());
        String FName = FNameTxt.getText();
        String LName = LNameTxt.getText();
        String Add = AddTxt.getText();
        String City = CityTxt.getText();
        String Email = EmailTxt.getText();
        String MNo = ContMTxt.getText();
        String WNo = ContWTxt.getText();

        if (Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", EmailTxt.getText())) {
            try {
                //initialized on top

                sta = con.prepareStatement("UPDATE customer SET f_name=?,l_name=?,address=?,city=?,email=?,M_No=?,W_No=? WHERE Cus_id=?");
                sta.setString(1, FName);
                sta.setString(2, LName);
                sta.setString(3, Add);
                sta.setString(4, City);
                sta.setString(5, Email);
                sta.setString(6, MNo);
                sta.setString(7, WNo);
                sta.setInt(8, id);

                sta.executeUpdate();
                JOptionPane.showMessageDialog(this, "Customer Details Updated Successfully ", "CUSTOMER DETAILS", JOptionPane.INFORMATION_MESSAGE);
                ResetForm();
                UpdateTable();
                //resets the form
            } catch (SQLException ex) {
                Logger.getLogger(UserRegUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Email Address", "CUSTOMER DETAILS", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void CusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) CusTable.getModel();
        int row = CusTable.getSelectedRow();

        FNameTxt.setText((String) model.getValueAt(row, 1).toString());
        LNameTxt.setText((String) model.getValueAt(row, 2).toString());
        AddTxt.setText((String) model.getValueAt(row, 3).toString());
        CityTxt.setText((String) model.getValueAt(row, 4).toString());
        EmailTxt.setText((String) model.getValueAt(row, 5).toString());
        ContMTxt.setText((String) model.getValueAt(row, 6).toString());
        ContWTxt.setText((String) model.getValueAt(row, 7).toString());
    }//GEN-LAST:event_CusTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CusViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CusViewUI().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddTxt;
    private javax.swing.JTextField CityTxt;
    private javax.swing.JFormattedTextField ContMTxt;
    private javax.swing.JFormattedTextField ContWTxt;
    private javax.swing.JLabel CusLbl;
    private javax.swing.JTable CusTable;
    private javax.swing.JButton DFelBtn;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel ExitLbl;
    private javax.swing.JTextField FNameTxt;
    private javax.swing.JLabel GRnLbl;
    private javax.swing.JLabel InvLbl;
    private javax.swing.JLabel ItemLbl;
    private javax.swing.JTextField LNameTxt;
    private javax.swing.JLabel LoginLbl;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JLabel RepoLbl;
    private javax.swing.JLabel SupLbl;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel UserLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
