/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IMSUIs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sriyanjith Herath
 */
public final class ItemViewUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuUI
     */
    public ItemViewUI() {
        initComponents();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_db?zeroDateTimeBehavior=convertToNull", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        UpdateTable();

    }

    String Name;

    public ItemViewUI(String name) {
        initComponents();

    }

    Connection con;
    PreparedStatement sta;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        UserLbl = new javax.swing.JLabel();
        ItemLbl = new javax.swing.JLabel();
        GRnLbl = new javax.swing.JLabel();
        CusLbl = new javax.swing.JLabel();
        SupLbl = new javax.swing.JLabel();
        ExitLbl = new javax.swing.JLabel();
        InvLbl = new javax.swing.JLabel();
        RepoLbl = new javax.swing.JLabel();
        LoginLbl = new javax.swing.JLabel();
        LogoPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ModTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SupTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        SPriceTxt = new javax.swing.JFormattedTextField();
        ItemCatCmb = new javax.swing.JComboBox<>();
        WarCmb = new javax.swing.JComboBox<>();
        DFelBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELECTRO WORLD");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        UserLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserLbl.setForeground(new java.awt.Color(255, 255, 255));
        UserLbl.setText(" User Registration");
        UserLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserLblMouseClicked(evt);
            }
        });

        ItemLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ItemLbl.setForeground(new java.awt.Color(255, 255, 255));
        ItemLbl.setText(" Item Registration");
        ItemLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ItemLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemLblMouseClicked(evt);
            }
        });

        GRnLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GRnLbl.setForeground(new java.awt.Color(255, 255, 255));
        GRnLbl.setText(" GRN");
        GRnLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        GRnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRnLblMouseClicked(evt);
            }
        });

        CusLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CusLbl.setForeground(new java.awt.Color(255, 255, 255));
        CusLbl.setText(" Customer Registration");
        CusLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CusLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusLblMouseClicked(evt);
            }
        });

        SupLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SupLbl.setForeground(new java.awt.Color(255, 255, 255));
        SupLbl.setText(" Supplier Registration");
        SupLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SupLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupLblMouseClicked(evt);
            }
        });

        ExitLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExitLbl.setForeground(new java.awt.Color(255, 255, 255));
        ExitLbl.setText(" Exit");
        ExitLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLblMouseClicked(evt);
            }
        });

        InvLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InvLbl.setForeground(new java.awt.Color(255, 255, 255));
        InvLbl.setText(" Invoice");
        InvLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InvLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvLblMouseClicked(evt);
            }
        });

        RepoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RepoLbl.setForeground(new java.awt.Color(0, 153, 204));
        RepoLbl.setText(" Search");
        RepoLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RepoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepoLblMouseClicked(evt);
            }
        });

        LoginLbl.setBackground(new java.awt.Color(102, 255, 255));
        LoginLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginLbl.setForeground(new java.awt.Color(255, 255, 255));
        LoginLbl.setText(" User Login");
        LoginLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SupLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GRnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InvLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CusLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(ExitLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RepoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(LoginLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InvLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LogoPanel.setBackground(new java.awt.Color(51, 51, 51));
        LogoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LogoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Inventory");

        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Item Model", "Item Category", "Item Supplier", "Warranty period", "Selling price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ItemTable);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ModTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Item Supplier");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Item Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Item Model");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Warranty Period");

        SupTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Item Category");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Selling Price     Rs.");

        NameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        SPriceTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(#,##0.00)"))));
        SPriceTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ItemCatCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ItemCatCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Television", "Refrigerator", "Audio Setup", "Laptop", "DVD", "Rice cooker", "Blender", "Mixer Grinder", "Fan", "Vaccum Cleaner", "Swing Machine", "Electric kettle", "Gas Cooker", "Radio", "Oven", "Washing Machine", "Air Conditioner", "Defreezer", " ", " ", " " }));

        WarCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        WarCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Month", "3 Months", "6 Months", "1 Year", "2 Years", "5 Year" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ModTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupTxt)
                            .addComponent(ItemCatCmb, javax.swing.GroupLayout.Alignment.LEADING, 0, 231, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SPriceTxt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NameTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ModTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemCatCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(WarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(SPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        DFelBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DFelBtn.setText("DELETE");
        DFelBtn.setPreferredSize(new java.awt.Dimension(67, 25));
        DFelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFelBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DFelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DFelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBtn))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void UpdateTable() {
        try {
            int c;
            sta = con.prepareStatement("SELECT * FROM item");
            ResultSet res = sta.executeQuery();

            ResultSetMetaData rsd = res.getMetaData();
            c = rsd.getColumnCount();

            DefaultTableModel model1 = (DefaultTableModel) ItemTable.getModel();
            model1.setRowCount(0);

            while (res.next()) {
                Vector vec = new Vector();
                for (int i = 0; i <= c; i++) {
                    vec.add(res.getString("Item_id"));
                    vec.add(res.getString("name"));
                    vec.add(res.getString("model"));
                    vec.add(res.getString("category"));
                    vec.add(res.getString("sup_id"));
                    vec.add(res.getString("warranty"));
                    vec.add(res.getString("sell_price"));
                }
                model1.addRow(vec);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ItemViewUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ResetForm() {
        NameTxt.setText("");
        ModTxt.setText("");
        ItemCatCmb.setSelectedIndex(-1);
        SupTxt.setText("");
        WarCmb.setSelectedIndex(-1);
        SPriceTxt.setText("");

    }

    private void LoginLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLblMouseClicked
        this.hide();
        new LoginUI().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_LoginLblMouseClicked

    private void UserLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLblMouseClicked
        this.hide();
        new UserRegUI().setVisible(true);
    }//GEN-LAST:event_UserLblMouseClicked

    private void SupLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupLblMouseClicked
        this.hide();
        new SupRegUI().setVisible(true);
    }//GEN-LAST:event_SupLblMouseClicked

    private void ItemLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemLblMouseClicked
        this.hide();
        new ItemRegUI().setVisible(true);
    }//GEN-LAST:event_ItemLblMouseClicked

    private void CusLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusLblMouseClicked
        this.hide();
        new CusRegUI().setVisible(true);
    }//GEN-LAST:event_CusLblMouseClicked

    private void InvLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvLblMouseClicked
        this.hide();
        new InvoiceUI().setVisible(true);
    }//GEN-LAST:event_InvLblMouseClicked

    private void GRnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRnLblMouseClicked
        this.hide();
        new GRNUI().setVisible(true);    }//GEN-LAST:event_GRnLblMouseClicked

    private void RepoLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepoLblMouseClicked
        this.hide();
        new SearchUI().setVisible(true);
    }//GEN-LAST:event_RepoLblMouseClicked

    private void ExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLblMouseClicked

    private void LogoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoPanelMouseClicked
        this.hide();
        new MenuUI().setVisible(true);
    }//GEN-LAST:event_LogoPanelMouseClicked

    private void DFelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFelBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) ItemTable.getModel();
        int row = ItemTable.getSelectedRow();

        int id = Integer.parseInt(model.getValueAt(row, 0).toString());
        
        int resDialog = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "ITEM DETAILS", JOptionPane.YES_NO_OPTION);
        
        if (resDialog == JOptionPane.YES_OPTION){
            try {
                //initialized on top

                sta = con.prepareStatement("DELETE FROM item WHERE item_id=?");
                sta.setInt(1,id);

                sta.executeUpdate();
                JOptionPane.showMessageDialog(this, "Item deleted Successfully ", "ITEM DETAILS", JOptionPane.INFORMATION_MESSAGE);
                ResetForm();
                UpdateTable();
                
            } catch (SQLException ex) {
                Logger.getLogger(UserRegUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_DFelBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) ItemTable.getModel();
        int row = ItemTable.getSelectedRow();

        int id = Integer.parseInt(model.getValueAt(row, 0).toString());
        String IName = NameTxt.getText();
        String Mod = ModTxt.getText();
        String Cat = ItemCatCmb.getSelectedItem().toString();
        String Sup = SupTxt.getText();
        String War = WarCmb.getSelectedItem().toString();
        String SPrice = SPriceTxt.getText();

        if (Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", SupTxt.getText())) {
            try {
                //initialized on top

                sta = con.prepareStatement("UPDATE item SET name=?,model=?,category=?,sup_id=?,warranty=?,sell_price=? WHERE item_id=?");
                sta.setString(1, IName);
                sta.setString(2, Mod);
                sta.setString(3, Cat);
                sta.setString(4, Sup);
                sta.setString(5, War);
                sta.setString(6, SPrice);
                sta.setInt(7, id);

                sta.executeUpdate();
                JOptionPane.showMessageDialog(this, "Customer Details Updated Successfully ", "CUSTOMER DETAILS", JOptionPane.INFORMATION_MESSAGE);
                ResetForm();
                UpdateTable();
                //resets the form
            } catch (SQLException ex) {
                Logger.getLogger(UserRegUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Email Address", "CUSTOMER DETAILS", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void ItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) ItemTable.getModel();
        int row = ItemTable.getSelectedRow();

        NameTxt.setText((String) model.getValueAt(row, 1).toString());
        ModTxt.setText((String) model.getValueAt(row, 2).toString());
        ItemCatCmb.setSelectedItem((String) model.getValueAt(row, 3).toString());
        SupTxt.setText((String) model.getValueAt(row, 4).toString());
        WarCmb.setSelectedItem((String) model.getValueAt(row, 5).toString());
        SPriceTxt.setText((String) model.getValueAt(row, 6).toString());
       
    }//GEN-LAST:event_ItemTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ItemViewUI().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CusLbl;
    private javax.swing.JButton DFelBtn;
    private javax.swing.JLabel ExitLbl;
    private javax.swing.JLabel GRnLbl;
    private javax.swing.JLabel InvLbl;
    private javax.swing.JComboBox<String> ItemCatCmb;
    private javax.swing.JLabel ItemLbl;
    private javax.swing.JTable ItemTable;
    private javax.swing.JLabel LoginLbl;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JTextField ModTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel RepoLbl;
    private javax.swing.JFormattedTextField SPriceTxt;
    private javax.swing.JLabel SupLbl;
    private javax.swing.JTextField SupTxt;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel UserLbl;
    private javax.swing.JComboBox<String> WarCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
