/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IMSUIs;

import java.awt.Frame;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sriyanjith Herath
 */
public class ItemRegUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuUI
     */
    public ItemRegUI() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_db?zeroDateTimeBehavior=convertToNull", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        //ItemIDUpdate();
    }
    Connection con;
    PreparedStatement sta;

    /*public void ItemIDUpdate(){
        try {
            
            
            sta = con.prepareStatement(1+ "SELECT LAST_INSERT_ID FROM item");
            ResultSet resItemID = sta.executeQuery();
            ItemIDLbl.setText("ITM"+resItemID);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ItemIDLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ItemNTxt = new javax.swing.JTextField();
        ItemMTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SupIDTxt = new javax.swing.JTextField();
        RegBtn = new javax.swing.JButton();
        RstBtn = new javax.swing.JButton();
        WarCmb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ItemCatCmb = new javax.swing.JComboBox<>();
        SupSchBtn = new javax.swing.JButton();
        SPriceTxt = new javax.swing.JFormattedTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        UserLbl6 = new javax.swing.JLabel();
        ItemLbl6 = new javax.swing.JLabel();
        GRnLbl6 = new javax.swing.JLabel();
        CusLbl6 = new javax.swing.JLabel();
        SupLbl6 = new javax.swing.JLabel();
        ExitLbl6 = new javax.swing.JLabel();
        InvLbl6 = new javax.swing.JLabel();
        RepoLbl6 = new javax.swing.JLabel();
        LoginLbl6 = new javax.swing.JLabel();
        LogoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELECTRO WORLD");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  Item Registration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Item ID");

        ItemIDLbl.setBackground(new java.awt.Color(204, 204, 255));
        ItemIDLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ItemIDLbl.setText("ITM");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Item Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Item Model");

        ItemNTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ItemMTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Warranty period");

        SupIDTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        RegBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegBtn.setText("REGISTER");
        RegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegBtnActionPerformed(evt);
            }
        });

        RstBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RstBtn.setText("RESET");
        RstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RstBtnActionPerformed(evt);
            }
        });

        WarCmb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WarCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Month", "3 Months", "6 Months", "1 Year", "2 Years", "5 Year" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Selling Price     Rs.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Item Category");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Supplier ID");

        ItemCatCmb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ItemCatCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Television", "Refrigerator", "Audio Setup", "Laptop", "DVD", "Rice cooker", "Blender", "Mixer Grinder", "Fan", "Vaccum Cleaner", "Swing Machine", "Electric kettle", "Gas Cooker", "Radio", "Oven", "Washing Machine", "Air Conditioner", "Defreezer", " ", " ", " " }));

        SupSchBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SupSchBtn.setText("SEARCH SUPPLIER");
        SupSchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupSchBtnActionPerformed(evt);
            }
        });

        SPriceTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(#,##0.00)"))));
        SPriceTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(56, 56, 56)
                                        .addComponent(ItemIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(ItemNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(WarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SupIDTxt)
                                            .addComponent(ItemCatCmb, 0, 266, Short.MAX_VALUE)
                                            .addComponent(SPriceTxt))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SupSchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ItemIDLbl))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ItemCatCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(SupSchBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(WarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(SPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));

        jPanel16.setBackground(new java.awt.Color(51, 51, 51));

        UserLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserLbl6.setForeground(new java.awt.Color(255, 255, 255));
        UserLbl6.setText(" User Registration");
        UserLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserLbl6MouseClicked(evt);
            }
        });

        ItemLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ItemLbl6.setForeground(new java.awt.Color(0, 204, 255));
        ItemLbl6.setText(" Item Registration");
        ItemLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ItemLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemLbl6MouseClicked(evt);
            }
        });

        GRnLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GRnLbl6.setForeground(new java.awt.Color(255, 255, 255));
        GRnLbl6.setText(" GRN");
        GRnLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        GRnLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRnLbl6MouseClicked(evt);
            }
        });

        CusLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CusLbl6.setForeground(new java.awt.Color(255, 255, 255));
        CusLbl6.setText(" Customer Registration");
        CusLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CusLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusLbl6MouseClicked(evt);
            }
        });

        SupLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SupLbl6.setForeground(new java.awt.Color(255, 255, 255));
        SupLbl6.setText(" Supplier Registration");
        SupLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SupLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupLbl6MouseClicked(evt);
            }
        });

        ExitLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExitLbl6.setForeground(new java.awt.Color(255, 255, 255));
        ExitLbl6.setText(" Exit");
        ExitLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ExitLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLbl6MouseClicked(evt);
            }
        });

        InvLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InvLbl6.setForeground(new java.awt.Color(255, 255, 255));
        InvLbl6.setText(" Invoice");
        InvLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InvLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvLbl6MouseClicked(evt);
            }
        });

        RepoLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RepoLbl6.setForeground(new java.awt.Color(255, 255, 255));
        RepoLbl6.setText(" Search");
        RepoLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RepoLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepoLbl6MouseClicked(evt);
            }
        });

        LoginLbl6.setBackground(new java.awt.Color(102, 255, 255));
        LoginLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginLbl6.setForeground(new java.awt.Color(255, 255, 255));
        LoginLbl6.setText(" User Login");
        LoginLbl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginLbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLbl6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SupLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GRnLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InvLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CusLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(ExitLbl6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RepoLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(LoginLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CusLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InvLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRnLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepoLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LogoPanel.setBackground(new java.awt.Color(51, 51, 51));
        LogoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegBtnActionPerformed
        String Name = ItemNTxt.getText();
        String Model = ItemMTxt.getText();
        String Cat = ItemCatCmb.getSelectedItem().toString();
        String SupID = SupIDTxt.getText();
        String Warr = WarCmb.getSelectedItem().toString();
        String SPrice = SPriceTxt.getText();

        try {
            //initialized on top

            sta = con.prepareStatement("INSERT INTO item(name,model,category,sup_id,warranty,sell_price)VALUES(?,?,?,?,?,?);");
            sta.setString(1, Name);
            sta.setString(2, Model);
            sta.setString(3, Cat);
            sta.setString(4, SupID);
            sta.setString(5, Warr);
            sta.setString(6, SPrice);

            sta.executeUpdate();
            JOptionPane.showMessageDialog(this, "ITEM REGISTERED SUCCESSFULLY ", "ITEM REGISTRATION", HEIGHT);

            //resets the form
            ItemNTxt.setText("");
            ItemMTxt.setText("");
            SPriceTxt.setText("");
            SupIDTxt.setText("");
            WarCmb.setSelectedIndex(-1);
            ItemCatCmb.setSelectedIndex(-1);

        } catch (SQLException ex) {
            Logger.getLogger(UserRegUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RegBtnActionPerformed

    private void RstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RstBtnActionPerformed

        ItemNTxt.setText("");
        ItemMTxt.setText("");
        SPriceTxt.setText("");
        SupIDTxt.setText("");
        WarCmb.setSelectedIndex(-1);
        ItemCatCmb.setSelectedIndex(-1);


    }//GEN-LAST:event_RstBtnActionPerformed

    private void SupSchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupSchBtnActionPerformed
        this.hide();
        new SupViewUI().setVisible(true);
    }//GEN-LAST:event_SupSchBtnActionPerformed

    private void UserLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLbl6MouseClicked
        this.hide();
        new UserRegUI().setVisible(true);
    }//GEN-LAST:event_UserLbl6MouseClicked

    private void ItemLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemLbl6MouseClicked
        this.hide();
        new ItemRegUI().setVisible(true);
    }//GEN-LAST:event_ItemLbl6MouseClicked

    private void GRnLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRnLbl6MouseClicked
        this.hide();
        new GRNUI().setVisible(true);
    }//GEN-LAST:event_GRnLbl6MouseClicked

    private void CusLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusLbl6MouseClicked
        this.hide();
        new CusRegUI().setVisible(true);
    }//GEN-LAST:event_CusLbl6MouseClicked

    private void SupLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupLbl6MouseClicked
        this.hide();
        new SupRegUI().setVisible(true);
    }//GEN-LAST:event_SupLbl6MouseClicked

    private void ExitLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLbl6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLbl6MouseClicked

    private void InvLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvLbl6MouseClicked
        this.hide();
        new InvoiceUI().setVisible(true);
    }//GEN-LAST:event_InvLbl6MouseClicked

    private void RepoLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepoLbl6MouseClicked
        this.hide();
        new SearchUI().setVisible(true);
    }//GEN-LAST:event_RepoLbl6MouseClicked

    private void LoginLbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLbl6MouseClicked
        this.hide();
        new LoginUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginLbl6MouseClicked

    private void LogoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoPanelMouseClicked
        this.hide();
        new MenuUI().setVisible(true);
    }//GEN-LAST:event_LogoPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemRegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ItemRegUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CusLbl6;
    private javax.swing.JLabel ExitLbl6;
    private javax.swing.JLabel GRnLbl6;
    private javax.swing.JLabel InvLbl6;
    private javax.swing.JComboBox<String> ItemCatCmb;
    private javax.swing.JLabel ItemIDLbl;
    private javax.swing.JLabel ItemLbl6;
    private javax.swing.JTextField ItemMTxt;
    private javax.swing.JTextField ItemNTxt;
    private javax.swing.JLabel LoginLbl6;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JButton RegBtn;
    private javax.swing.JLabel RepoLbl6;
    private javax.swing.JButton RstBtn;
    private javax.swing.JFormattedTextField SPriceTxt;
    private javax.swing.JTextField SupIDTxt;
    private javax.swing.JLabel SupLbl6;
    private javax.swing.JButton SupSchBtn;
    private javax.swing.JLabel UserLbl6;
    private javax.swing.JComboBox<String> WarCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
