/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IMSUIs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sriyanjith Herath
 */
public class UserRegUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuUI
     */
    public UserRegUI() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_db?zeroDateTimeBehavior=convertToNull", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    Connection con;
    PreparedStatement sta;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UNameTxt = new javax.swing.JTextField();
        PwdTxt = new javax.swing.JPasswordField();
        cPwdTxt = new javax.swing.JPasswordField();
        URegBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        UserLbl3 = new javax.swing.JLabel();
        ItemLbl3 = new javax.swing.JLabel();
        GRnLbl3 = new javax.swing.JLabel();
        CusLbl3 = new javax.swing.JLabel();
        SupLbl3 = new javax.swing.JLabel();
        ExitLbl3 = new javax.swing.JLabel();
        InvLbl3 = new javax.swing.JLabel();
        RepoLbl3 = new javax.swing.JLabel();
        LoginLbl3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELECTRO WORLD");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" User Registration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Confirm password");

        UNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PwdTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cPwdTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        URegBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        URegBtn.setText("Register");
        URegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URegBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addGap(337, 337, 337))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(URegBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(91, 91, 91))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(95, 95, 95)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UNameTxt)
                                    .addComponent(PwdTxt)
                                    .addComponent(cPwdTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cPwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(URegBtn)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));

        UserLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserLbl3.setForeground(new java.awt.Color(0, 204, 255));
        UserLbl3.setText(" User Registration");
        UserLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserLbl3MouseClicked(evt);
            }
        });

        ItemLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ItemLbl3.setForeground(new java.awt.Color(255, 255, 255));
        ItemLbl3.setText(" Item Registration");
        ItemLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ItemLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemLbl3MouseClicked(evt);
            }
        });

        GRnLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GRnLbl3.setForeground(new java.awt.Color(255, 255, 255));
        GRnLbl3.setText(" GRN");
        GRnLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        GRnLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRnLbl3MouseClicked(evt);
            }
        });

        CusLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CusLbl3.setForeground(new java.awt.Color(255, 255, 255));
        CusLbl3.setText(" Customer Registration");
        CusLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CusLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusLbl3MouseClicked(evt);
            }
        });

        SupLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SupLbl3.setForeground(new java.awt.Color(255, 255, 255));
        SupLbl3.setText(" Supplier Registration");
        SupLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SupLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupLbl3MouseClicked(evt);
            }
        });

        ExitLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExitLbl3.setForeground(new java.awt.Color(255, 255, 255));
        ExitLbl3.setText(" Exit");
        ExitLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ExitLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLbl3MouseClicked(evt);
            }
        });

        InvLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InvLbl3.setForeground(new java.awt.Color(255, 255, 255));
        InvLbl3.setText(" Invoice");
        InvLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InvLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvLbl3MouseClicked(evt);
            }
        });

        RepoLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RepoLbl3.setForeground(new java.awt.Color(255, 255, 255));
        RepoLbl3.setText(" Search");
        RepoLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RepoLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepoLbl3MouseClicked(evt);
            }
        });

        LoginLbl3.setBackground(new java.awt.Color(102, 255, 255));
        LoginLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginLbl3.setForeground(new java.awt.Color(255, 255, 255));
        LoginLbl3.setText(" User Login");
        LoginLbl3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLbl3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SupLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GRnLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InvLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CusLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(ExitLbl3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RepoLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(LoginLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CusLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InvLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRnLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepoLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void URegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URegBtnActionPerformed
        String Uname = UNameTxt.getText();
        String Pwd = PwdTxt.getText();
        String cPwd = cPwdTxt.getText();
        boolean exist = false;

        if (Pwd == null ? cPwd == null : Pwd.equals(cPwd)) {
            try {
                sta = con.prepareStatement("SELECT * FROM user;");
                ResultSet resUser = sta.executeQuery();
                while (resUser.next()) {
                    if (resUser.getString("username").equals(Uname)) {
                        exist = true;
                    }
                }
                if (exist == true) {
                    JOptionPane.showMessageDialog(this, "EXISTING USERNAME! PLEASE TRY ANOTHER USERNAME ", "USER REGISTRATION", HEIGHT);
                    //resets form
                    exist = false;
                    UNameTxt.setText("");
                    PwdTxt.setText("");
                    cPwdTxt.setText("");
                    UNameTxt.requestFocus();
                } else {
                    try {
                        sta = con.prepareStatement("INSERT INTO user(username,password) VALUES(?,?);");
                        sta.setString(1, Uname);
                        sta.setString(2, Pwd);
                        sta.executeUpdate();

                        JOptionPane.showMessageDialog(this, "USER REGISTERED SUCCESSFULLY, LOGIN WITH NEW USERNAME AND PASSWORD ", "USER REGISTRATION", HEIGHT);
                        this.hide();
                        new LoginUI().setVisible(true);

                    } catch (SQLException ex) {
                        Logger.getLogger(UserRegUI.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "EXISTING USERNAME! PLEASE TRY ANOTHER USERNAME ", "USER REGISTRATION", HEIGHT);
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(UserRegUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "PASSWORD CONFIRMATION DO NOT MATCH !", "USER REGISTRATION", HEIGHT);
            PwdTxt.setText("");//reset password fields
            cPwdTxt.setText("");
            PwdTxt.requestFocus();
        }

    }//GEN-LAST:event_URegBtnActionPerformed

    private void UserLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLbl3MouseClicked
        this.hide();
        new UserRegUI().setVisible(true);
    }//GEN-LAST:event_UserLbl3MouseClicked

    private void ItemLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemLbl3MouseClicked
        this.hide();
        new ItemRegUI().setVisible(true);
    }//GEN-LAST:event_ItemLbl3MouseClicked

    private void GRnLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRnLbl3MouseClicked
        this.hide();
    }//GEN-LAST:event_GRnLbl3MouseClicked

    private void CusLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusLbl3MouseClicked
        this.hide();
        new CusRegUI().setVisible(true);
    }//GEN-LAST:event_CusLbl3MouseClicked

    private void SupLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupLbl3MouseClicked
        this.hide();
        new SupRegUI().setVisible(true);
    }//GEN-LAST:event_SupLbl3MouseClicked

    private void ExitLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLbl3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLbl3MouseClicked

    private void InvLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvLbl3MouseClicked
        this.hide();
        new InvoiceUI().setVisible(true);
    }//GEN-LAST:event_InvLbl3MouseClicked

    private void RepoLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepoLbl3MouseClicked
        this.hide();
        new SearchUI().setVisible(true);
    }//GEN-LAST:event_RepoLbl3MouseClicked

    private void LoginLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLbl3MouseClicked
        this.hide();
        new LoginUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginLbl3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UserRegUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CusLbl3;
    private javax.swing.JLabel ExitLbl3;
    private javax.swing.JLabel GRnLbl3;
    private javax.swing.JLabel InvLbl3;
    private javax.swing.JLabel ItemLbl3;
    private javax.swing.JLabel LoginLbl3;
    private javax.swing.JPasswordField PwdTxt;
    private javax.swing.JLabel RepoLbl3;
    private javax.swing.JLabel SupLbl3;
    private javax.swing.JTextField UNameTxt;
    private javax.swing.JButton URegBtn;
    private javax.swing.JLabel UserLbl3;
    private javax.swing.JPasswordField cPwdTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
